### ISSUE TITLE
@"@pause" instead of @"pause"?

### ISSUE THREAD

**Issue by Heshyo** [leon/cordova-plugin-remotecommand#2]
In the `enabled` function in https://github.com/leon/cordova-plugin-remotecommand/blob/master/src/ios/MRemoteCommand.m I see
`if ([cmd isEqual: @"@pause"]) {`
Shouldn't it be
`if ([cmd isEqual: @"pause"]) {`
like all other commands?

**Comment by leon** [comment]
Fixed in version 1.0.2
